In [1]:
import numpy

In [87]:
def vecteur_puissance_k(T,k=1):
    
    V_k=[]
    for d in range(1,k+1):
        V_k.append(numpy.array([(i+1)**d for i in range(T)]))
    
    M=numpy.vstack((numpy.ones(T),[V_k[d] for d in range(k)])).T
    
    return M

In [88]:
vecteur_puissance_k(T=6,k=3)

array([[  1.,   1.,   1.,   1.],
       [  1.,   2.,   4.,   8.],
       [  1.,   3.,   9.,  27.],
       [  1.,   4.,  16.,  64.],
       [  1.,   5.,  25., 125.],
       [  1.,   6.,  36., 216.]])

In [54]:
def Polynome_Estimation(data,odre=1):
    T=len(data)
    M=vecteur_puissance_k(T,k=odre)
    
    S1=numpy.matmul(M.T,M)
    S2=numpy.linalg.inv(S1)
    S3=numpy.matmul(data.T,M)
    Estimateurs=numpy.matmul(S2,S3)
    
    return Estimateurs

In [75]:
def valeur_polynome(data,coefficients):
    data=numpy.array(data)
    k=len(coefficients)
    P_X=numpy.array(list(coefficients[j]*(data**j) for j in range(k)))
    return sum(P_X)

In [76]:
dx=[1,4,6,4]
coeff=[1,-1,2]
SS=valeur_polynome(dx,coeff)
print(SS)

[ 2 29 67 29]


In [80]:
def Polynome_ajustement(data,degre=1):
    %matplotlib inline
    import matplotlib.pyplot as plt
    
    T=len(data)
    
    # récupérer l'estimateur
    theta=Polynome_Estimation(data,odre=degre)

    
    ## variance d'erreurs
    MM=vecteur_puissance_k(len(data),k=degre)
    E=data-numpy.dot(MM , theta)
    
    variance_erreurs=numpy.dot(E,E)/(1.0*(len(data)-len(theta)+1))
    print("variance_erreurs=%.4f"%variance_erreurs)
    return variance_erreurs

In [91]:
h=lambda x : 2+3*x-3*x**2+x**3
donnees=numpy.array([h(x)+numpy.random.normal(0,2) for x in range(1,21)])

len(donnees)
vecteur_puissance_k(20,k=3)

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 2.000e+00, 4.000e+00, 8.000e+00],
       [1.000e+00, 3.000e+00, 9.000e+00, 2.700e+01],
       [1.000e+00, 4.000e+00, 1.600e+01, 6.400e+01],
       [1.000e+00, 5.000e+00, 2.500e+01, 1.250e+02],
       [1.000e+00, 6.000e+00, 3.600e+01, 2.160e+02],
       [1.000e+00, 7.000e+00, 4.900e+01, 3.430e+02],
       [1.000e+00, 8.000e+00, 6.400e+01, 5.120e+02],
       [1.000e+00, 9.000e+00, 8.100e+01, 7.290e+02],
       [1.000e+00, 1.000e+01, 1.000e+02, 1.000e+03],
       [1.000e+00, 1.100e+01, 1.210e+02, 1.331e+03],
       [1.000e+00, 1.200e+01, 1.440e+02, 1.728e+03],
       [1.000e+00, 1.300e+01, 1.690e+02, 2.197e+03],
       [1.000e+00, 1.400e+01, 1.960e+02, 2.744e+03],
       [1.000e+00, 1.500e+01, 2.250e+02, 3.375e+03],
       [1.000e+00, 1.600e+01, 2.560e+02, 4.096e+03],
       [1.000e+00, 1.700e+01, 2.890e+02, 4.913e+03],
       [1.000e+00, 1.800e+01, 3.240e+02, 5.832e+03],
       [1.000e+00, 1.900e+01, 3.610e+02, 6.859

In [84]:
Polynome_ajustement(donnees,degre=3)



variance_erreurs=4.1701


4.170089698512875

In [142]:
import random
import numpy
import scipy.optimize as opt
def tendance_puissance(data):
    data = numpy.array(data)
    def objectif (alpha,t):
        return data-alpha[0]-alpha[1]*alpha[2]**t #diff element par element
    a0=numpy.array([random.random() for _ in range(3)])
    tt=[i for i in range(1,len(data)+1)]
    r=opt.leastsq(objectif,a0,args=(tt))[0] ##Parce que cette fonction retourne plusieurs valeurs [result, eval, error]
    return r


In [286]:
import random
import numpy
import scipy.optimize as opt
def tendance_polynomiale(data):
    data = numpy.array(data)
    def objectif (alpha,t):
        return data-alpha[0]-alpha[1]*t#diff element par element
    a0=numpy.array([random.random() for _ in range(3)])
    tt=[i for i in range(1,len(data)+1)]
    tt = numpy.array(tt)
    r=opt.leastsq(objectif,a0,args=(tt))[0] ##Parce que cette fonction retourne plusieurs valeurs [result, eval, error]
    return r


In [1]:
N = 10000
er= numpy.random.normal(0,2,N)

data = []
import numpy
for t in range(N):
    data.append(1+2*t+3*t**2+er[t])
    
tendance_logisitque(data)



NameError: name 'numpy' is not defined