# Tp 2 Regression lineaire

In [90]:
import numpy
T = 15
X1 = numpy.ones(T)
X1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
XX=numpy.array([i+1 for i in range(len(X1))])
print(XX)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [92]:
MM=numpy.vstack((X1,XX)).T
print(MM)

[[ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]
 [ 1. 10.]
 [ 1. 11.]
 [ 1. 12.]
 [ 1. 13.]
 [ 1. 14.]
 [ 1. 15.]]


In [93]:
g=lambda x : 2+3*x
XX

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [94]:
Y = numpy.array([g(x)+numpy.random.normal(0,1.5) for x in XX])
print(Y)
print("----"*20)

[ 6.81819127  9.54083448 11.79401602 13.89259849 19.09354437 16.40575422
 21.9930827  26.26078544 29.84235647 35.11345389 33.55956169 41.83927636
 41.98370197 44.54678112 46.43386965]
--------------------------------------------------------------------------------


In [95]:
S1=numpy.matmul(MM.T, MM)
S1

array([[  15.,  120.],
       [ 120., 1240.]])

In [96]:
S2=numpy.linalg.inv(S1)
S2

array([[ 0.2952381 , -0.02857143],
       [-0.02857143,  0.00357143]])

In [97]:
S3=numpy.matmul(Y, MM.T)

ValueError: shapes (15,) and (2,15) not aligned: 15 (dim 0) != 2 (dim 0)

In [98]:
S=numpy.matmul(S2, S3)
print("Estimateurs=",S)

Estimateurs= [2.77137749 2.91276628]


In [99]:
E=Y-numpy.dot(MM , S)
## variance d'erreurs
numpy.dot(E,E)/(1.0*len(X1))
S[0]

2.771377494988741

In [104]:
E=Y-numpy.dot(MM , S)
E

array([ 1.13404749,  0.94392442,  0.28433968, -0.52984413,  1.75833547,
       -3.84222097, -1.16765877,  0.18727769,  0.85608243,  3.21441358,
       -1.25224491,  4.11470348,  1.3463628 ,  0.99667568, -0.02900208])

array([[ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.],
       [ 1.,  4.],
       [ 1.,  5.],
       [ 1.,  6.],
       [ 1.,  7.],
       [ 1.,  8.],
       [ 1.,  9.],
       [ 1., 10.],
       [ 1., 11.],
       [ 1., 12.],
       [ 1., 13.],
       [ 1., 14.],
       [ 1., 15.]])