In [135]:
import numpy

data= numpy.random.poisson(3,19)

data
len(data)

19

In [2]:
X1 = data[:3]
X2 = data[3:]

In [3]:
X1

array([3, 1, 2])

In [4]:
X2

array([0, 1, 6, 5, 3, 4, 1, 5, 5, 3, 3, 1, 5, 3, 5, 2])

# autoregressive Model p =1 

In [ ]:
S1 = sum
([data[t-1]*data[t-2] for t in range(2,len(data))])

164

import os
Liste_donnees=os.listdir('../DonCAC40/DonCAC40')
Liste_donnees

In [158]:
def Model_AR1(data):
    alpha1 = sum([data[t]*data[t-1] for t in range(1,len(data))])/sum([data[t-1]**2 for t in range(1,len(data))])
    return alpha1

In [159]:
import pandas as pd
F='../DonCAC40/DonCAC40/ORA.PA.csv'
data = pd.read_csv(F, delimiter=',')
data=data.dropna() # supprimer les données manquantes

DataOrange=data[data.columns[5]]
Model_AR1(DataOrange)

1.0000616205454524

Date       Open       High        Low      Close   AdjClose  \
0     2010-01-04  17.680000  17.775000  17.559999  17.760000   9.612064   
1     2010-01-05  17.745001  17.780001  17.639999  17.719999   9.590416   
2     2010-01-06  17.770000  17.780001  17.629999  17.665001   9.560650   
3     2010-01-07  17.660000  17.674999  17.334999  17.445000   9.441582   
4     2010-01-08  17.495001  17.530001  17.200001  17.330000   9.379341   
5     2010-01-11  17.400000  17.400000  17.150000  17.295000   9.360399   
6     2010-01-12  17.350000  17.450001  17.235001  17.350000   9.390165   
7     2010-01-13  17.400000  17.559999  17.350000  17.405001   9.419931   
8     2010-01-14  17.530001  17.535000  17.295000  17.320000   9.373928   
9     2010-01-15  17.389999  17.400000  17.014999  17.090000   9.249447   
10    2010-01-18  17.180000  17.190001  17.045000  17.100000   9.254862   
11    2010-01-19  17.120001  17.334999  17.090000  17.295000   9.360399   
12    2010-01-20  17.320000  17.395000  17.000000  17.010000   9.206151   
13    2010-01-21  17.055000  17.184999  16.924999  16.924999   9.160147   
14    2010-01-22  16.905001  17.235001  16.834999  16.920000   9.157439   
15    2010-01-25  16.840000  17.010000  16.825001  16.825001   9.106026   
16    2010-01-26  16.790001  16.860001  16.625000  16.860001   9.124967   
17    2010-01-27  16.809999  16.844999  16.655001  16.700001   9.038373   
18    2010-01-28  16.834999  16.915001  16.430000  16.430000   8.892242   
19    2010-01-29  16.455000  16.754999  16.450001  16.625000   8.997782   
20    2010-02-01  16.559999  16.889999  16.530001  16.795000   9.089788   
21    2010-02-02  16.820000  16.950001  16.750000  16.915001   9.154737   
22    2010-02-03  16.950001  17.020000  16.670000  16.719999   9.049197   
23    2010-02-04  16.719999  16.969999  16.500000  16.530001   8.946364   
24    2010-02-05  16.510000  16.730000  16.230000  16.230000   8.783998   
25    2010-02-08  16.230000  16.549999  16.230000  16.495001   8.927422   
26    2010-02-09  16.500000  16.535000  16.320000  16.420000   8.886831   
27    2010-02-10  16.480000  16.670000  16.424999  16.545000   8.954481   
28    2010-02-11  16.540001  16.650000  16.285000  16.445000   8.900360   
29    2010-02-12  16.520000  16.615000  16.385000  16.445000   8.900360   
...          ...        ...        ...        ...        ...        ...   
2292  2018-12-18  14.440000  14.480000  14.165000  14.225000  14.225000   
2293  2018-12-19  14.280000  14.385000  14.240000  14.355000  14.355000   
2294  2018-12-20  14.205000  14.320000  14.110000  14.265000  14.265000   
2295  2018-12-21  14.260000  14.300000  14.050000  14.175000  14.175000   
2296  2018-12-24  14.155000  14.160000  14.030000  14.105000  14.105000   
2297  2018-12-27  14.125000  14.180000  13.815000  13.950000  13.950000   
2298  2018-12-28  13.980000  14.175000  13.945000  14.080000  14.080000   
2299  2018-12-31  14.165000  14.185000  14.105000  14.155000  14.155000   
2300  2019-01-02  14.065000  14.185000  13.885000  14.095000  14.095000   
2301  2019-01-03  14.050000  14.240000  14.010000  14.180000  14.180000   
2302  2019-01-04  14.215000  14.320000  14.125000  14.280000  14.280000   
2303  2019-01-07  14.330000  14.340000  14.135000  14.200000  14.200000   
2304  2019-01-08  14.195000  14.250000  13.780000  13.780000  13.780000   
2305  2019-01-09  13.800000  13.825000  13.555000  13.730000  13.730000   
2306  2019-01-10  13.700000  13.815000  13.535000  13.570000  13.570000   
2307  2019-01-11  13.620000  13.830000  13.620000  13.770000  13.770000   
2308  2019-01-14  13.710000  13.745000  13.535000  13.555000  13.555000   
2309  2019-01-15  13.685000  13.715000  13.360000  13.460000  13.460000   
2310  2019-01-16  13.500000  13.505000  13.330000  13.400000  13.400000   
2311  2019-01-17  13.335000  13.480000  13.325000  13.445000  13.445000   
2312  2019-01-18  13.500000  13.610000  13.370000  13.570000  13.570000   
2313  2019-01-21  13.475000  13.49000

In [127]:
DataOrange=data["Close"]

# p > 1 general case 

In [128]:
DataOrange

0       17.760000
1       17.719999
2       17.665001
3       17.445000
4       17.330000
5       17.295000
6       17.350000
7       17.405001
8       17.320000
9       17.090000
10      17.100000
11      17.295000
12      17.010000
13      16.924999
14      16.920000
15      16.825001
16      16.860001
17      16.700001
18      16.430000
19      16.625000
20      16.795000
21      16.915001
22      16.719999
23      16.530001
24      16.230000
25      16.495001
26      16.420000
27      16.545000
28      16.445000
29      16.445000
          ...    
2292    14.225000
2293    14.355000
2294    14.265000
2295    14.175000
2296    14.105000
2297    13.950000
2298    14.080000
2299    14.155000
2300    14.095000
2301    14.180000
2302    14.280000
2303    14.200000
2304    13.780000
2305    13.730000
2306    13.570000
2307    13.770000
2308    13.555000
2309    13.460000
2310    13.400000
2311    13.445000
2312    13.570000
2313    13.450000
2314    13.360000
2315    13.380000
2316    13

In [155]:
def initial_Mp(p,data):
    Mp= numpy.empty([p, p]) # 3-lignes , 2-cols
    Bp= numpy.zeros(p)
    for i in range(0,p):
        #Mp[i,i]=sum([data[t-i]**2 for t in range(p,len(data))])
        Bp[i]=  sum([data[t]*data[t-i-1] for t in range(p,len(data))])
    for i in range(0,p):
        for j in range(0,p):
            Mp[i,j]= sum([data[t-i-1]*data[t-j-1] for t in range(p,len(data))])
   
    return numpy.linalg.solve(Mp, Bp) 
    #return Mp
    
    

In [161]:
initial_Mp(4,DataOrange)

array([ 1.00539806, -0.05890073,  0.04856708,  0.0050176 ])

array([ 0.99834513, -0.06163174,  0.0532155 ,  0.00981936])

array([ 1.00000000e+00, -2.26075785e-14,  7.00682764e-13, -6.64230602e-13])

In [131]:
p =4
Bp= numpy.empty([p,1])
Bp[3]

array([-2.57620251e-13])